### ISSUE TITLE
Incompatible with Sketch 70.6 on Mac Mini M1 2020 Big Sur 11.1

### ISSUE THREAD

**Issue by stijnbessem** [abynim/lippy#6]
<img width="480" alt="Screenshot 2021-03-09 at 17 25 07" src="https://user-images.githubusercontent.com/20166700/110503368-66d0b580-80fc-11eb-8653-c00f904093ad.png">

**Comment by abynim** [comment]
Thanks for reporting @stijnbessem. Can you please let me know if the latest update (v1.1.2) works for you? Don't have an M1 Mac to test it here. 

Note: you'll probably need to restart Sketch after updating.

**Comment by stijnbessem** [comment]
@abynim i apologise for not checking the latest version. beginner mistake. plugin is working as expected now. thanks for the reply!
